/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DonarRouteImport } from './routes/donar'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as HistoriasRouteImport } from './routes/historias'
import { Route as VoluntariadoRouteImport } from './routes/voluntariado'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonarRoute = DonarRouteImport.update({
  id: '/donar',
  path: '/donar',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriasRoute = HistoriasRouteImport.update({
  id: '/historias',
  path: '/historias',
  getParentRoute: () => rootRouteImport,
} as any)
const VoluntariadoRoute = VoluntariadoRouteImport.update({
  id: '/voluntariado',
  path: '/voluntariado',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/donar': typeof DonarRoute
  '/eventos': typeof EventosRoute
  '/historias': typeof HistoriasRoute
  '/voluntariado': typeof VoluntariadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/donar': typeof DonarRoute
  '/eventos': typeof EventosRoute
  '/historias': typeof HistoriasRoute
  '/voluntariado': typeof VoluntariadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/donar': typeof DonarRoute
  '/eventos': typeof EventosRoute
  '/historias': typeof HistoriasRoute
  '/voluntariado': typeof VoluntariadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/donar' | '/eventos' | '/historias' | '/voluntariado'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/donar' | '/eventos' | '/historias' | '/voluntariado'
  id: '__root__' | '/' | '/donar' | '/eventos' | '/historias' | '/voluntariado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DonarRoute: typeof DonarRoute
  EventosRoute: typeof EventosRoute
  HistoriasRoute: typeof HistoriasRoute
  VoluntariadoRoute: typeof VoluntariadoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donar': {
      id: '/donar'
      path: '/donar'
      fullPath: '/donar'
      preLoaderRoute: typeof DonarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historias': {
      id: '/historias'
      path: '/historias'
      fullPath: '/historias'
      preLoaderRoute: typeof HistoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voluntariado': {
      id: '/voluntariado'
      path: '/voluntariado'
      fullPath: '/voluntariado'
      preLoaderRoute: typeof VoluntariadoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DonarRoute: DonarRoute,
  EventosRoute: EventosRoute,
  HistoriasRoute: HistoriasRoute,
  VoluntariadoRoute: VoluntariadoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
